# Generated by Django 4.0.2 on 2022-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190907_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
