# Generated by Django 4.0.2 on 2022-05-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190903_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=520)),
                ('name', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=45)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
